# Generated by Django 6.0.4 on 2026-06-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefa_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
